const {find} = require('./find')
const Bucket = require('../data/Bucket')
const {test} = require('ava')
const {insertSomeData, numCompare, binder, api} = require('../utils/testutils')

test('insertions', (t) => {
	const {is, deepEqual:eq} = binder(t)
	let tree = new Bucket(1, 3, numCompare)
	tree = insertSomeData(api, tree)

	is(find(api, tree, 1), 'one')
	is(find(api, tree, 0), undefined)
	is(find(api, tree, 2), 'two')
	is(find(api, tree, 11), undefined)
	is(find(api, tree, 87), 'eighty-seven')
	is(find(api, tree, 88), 'eighty-eight')
	is(find(api, tree, 90), 'ninety')
	is(find(api, tree, 101), undefined)

	const mapRange = Array.from(tree.rangeIterator(api, 55, 86))
	eq(mapRange, [[55, 'fifty-five'], [56, 'fifty-six'], [57, 'fifty-seven'], [80, 'eighty'], [85, 'eighty-five'], [86, 'eighty-six']])
	eq(Array.from(tree.rangeIterator(api, 0, 3)), [[1, 'one'], [2, 'two'], [3, 'three']])
	eq(Array.from(tree.rangeIterator(api, 90, 300)), [[90, 'ninety']])
	eq(Array.from(tree.rangeIterator(api, 300, 1000)), [])
})